import '../../../core/config/app_config.dart';
import '../../../core/network/api_client.dart';
import '../models/schedule.dart';
import '../models/subscription_status.dart';
import '../models/subscription_view.dart';

/// MA-131 FR-1..FR-9. `DioSubscriptionRepository(ApiClient)` hits
/// `AppConfig.subscriptionBaseUrl`.
abstract class SubscriptionRepository {
  /// MA-131 FR-9. `GET /subscriptions/me`.
  Future<List<SubscriptionView>> list();

  /// MA-131 FR-1. `POST /subscriptions`. [idempotencyKey] is generated by
  /// the caller once per confirm attempt, same convention as
  /// `CartRepository.addItem`.
  Future<SubscriptionView> create({
    required String productId,
    required int quantity,
    required Schedule schedule,
    required DateTime startDate,
    required String slotId,
    required String idempotencyKey,
  });

  /// MA-131 FR-2. No `from`/`until` (both null) is an open-ended pause —
  /// the shape [SubscriptionView.isPausedIndefinitely] checks for.
  Future<void> pause(String id, {DateTime? from, DateTime? until});

  /// MA-131 FR-3.
  Future<void> resume(String id);

  /// MA-131 FR-4. Irreversible — matches the confirm-dialog gate on the
  /// detail sheet (MA-133 FR-5).
  Future<void> stop(String id);

  /// MA-131 FR-5. Throws [ApiException] with `errorCode: 'CUTOFF_PASSED'`
  /// (`409`) if the server's own cut-off has already passed for [date].
  Future<void> skip(String id, DateTime date);

  /// MA-131 FR-6. Returns the edit's effective date — `null` means it
  /// applied immediately (before the next cut-off); a non-null date later
  /// than the subscription's own next delivery means it was deferred to a
  /// [PendingEdit] instead (MA-133 FR-5's "Changes apply from {date}"
  /// notice). Deliberately **not** `Future<SubscriptionView>` — Subscription
  /// Service's own `edit()` returns only `{effectiveFrom}`, not a full
  /// detail response; the caller re-fetches via [list] for the updated view.
  Future<DateTime?> edit(String id, {int? quantity, Schedule? schedule});
}

class DioSubscriptionRepository implements SubscriptionRepository {
  DioSubscriptionRepository(this._client);

  final ApiClient _client;

  @override
  Future<List<SubscriptionView>> list() async {
    final data = await _client.request('GET', '${AppConfig.subscriptionBaseUrl}/subscriptions/me');
    final subscriptions = data['subscriptions'] as List? ?? const [];
    return subscriptions
        .map((s) => SubscriptionView.fromJson(s as Map<String, dynamic>))
        .toList();
  }

  @override
  Future<SubscriptionView> create({
    required String productId,
    required int quantity,
    required Schedule schedule,
    required DateTime startDate,
    required String slotId,
    required String idempotencyKey,
  }) async {
    final data = await _client.request(
      'POST',
      '${AppConfig.subscriptionBaseUrl}/subscriptions',
      body: {
        'productId': productId,
        'quantity': quantity,
        'schedule': schedule.toJson(),
        'startDate': startDate.toIso8601String().split('T').first,
        'slotId': slotId,
        'idempotencyKey': idempotencyKey,
      },
    );
    // Subscription Service's own create() response is a minimal
    // {subscriptionId, status, nextDeliveryDate} — not a full detail
    // response — so the rest of the view is filled in from what the
    // caller already knows it just requested.
    return SubscriptionView(
      id: data['subscriptionId'] as String,
      productId: productId,
      quantity: quantity,
      schedule: schedule,
      status: SubscriptionStatus.fromWire(data['status'] as String),
      nextDeliveryDate: data['nextDeliveryDate'] == null
          ? null
          : DateTime.parse(data['nextDeliveryDate'] as String),
    );
  }

  @override
  Future<void> pause(String id, {DateTime? from, DateTime? until}) async {
    await _client.request(
      'POST',
      '${AppConfig.subscriptionBaseUrl}/subscriptions/$id/pause',
      body: {
        if (from != null) 'from': from.toIso8601String().split('T').first,
        if (until != null) 'until': until.toIso8601String().split('T').first,
      },
    );
  }

  @override
  Future<void> resume(String id) async {
    await _client.request('POST', '${AppConfig.subscriptionBaseUrl}/subscriptions/$id/resume');
  }

  @override
  Future<void> stop(String id) async {
    await _client.request('POST', '${AppConfig.subscriptionBaseUrl}/subscriptions/$id/stop');
  }

  @override
  Future<void> skip(String id, DateTime date) async {
    await _client.request(
      'POST',
      '${AppConfig.subscriptionBaseUrl}/subscriptions/$id/skip',
      body: {'date': date.toIso8601String().split('T').first},
    );
  }

  @override
  Future<DateTime?> edit(String id, {int? quantity, Schedule? schedule}) async {
    final data = await _client.request(
      'PATCH',
      '${AppConfig.subscriptionBaseUrl}/subscriptions/$id',
      body: {
        'quantity': ?quantity,
        'schedule': ?schedule?.toJson(),
      },
    );
    final effectiveFrom = data['effectiveFrom'] as String?;
    return effectiveFrom == null ? null : DateTime.parse(effectiveFrom);
  }
}
