import 'package:flutter_secure_storage/flutter_secure_storage.dart';

/// Session tokens live only in secure storage, never in shared_preferences
/// or app memory persisted to disk — per both specs' NFR "Security: Tokens
/// only in secure storage; no PII in logs".
class SecureTokenStorage {
  SecureTokenStorage({FlutterSecureStorage? storage})
      : _storage = storage ?? const FlutterSecureStorage();

  final FlutterSecureStorage _storage;

  static const _accessTokenKey = 'milkful_access_token';
  static const _refreshTokenKey = 'milkful_refresh_token';
  static const _accessTokenExpiresAtKey = 'milkful_access_token_expires_at';

  Future<void> saveTokens({
    required String accessToken,
    required String refreshToken,
    required DateTime accessTokenExpiresAt,
  }) async {
    await Future.wait([
      _storage.write(key: _accessTokenKey, value: accessToken),
      _storage.write(key: _refreshTokenKey, value: refreshToken),
      _storage.write(
        key: _accessTokenExpiresAtKey,
        value: accessTokenExpiresAt.toIso8601String(),
      ),
    ]);
  }

  Future<String?> readAccessToken() => _read(_accessTokenKey);

  Future<String?> readRefreshToken() => _read(_refreshTokenKey);

  Future<DateTime?> readAccessTokenExpiresAt() async {
    final raw = await _read(_accessTokenExpiresAtKey);
    if (raw == null) return null;
    return DateTime.tryParse(raw);
  }

  /// `ApiClient` calls `readAccessToken` unconditionally on every request,
  /// including unauthenticated ones — see its constructor. On web,
  /// `flutter_secure_storage` encrypts every value with an AES-GCM key it
  /// keeps in localStorage; if that key and a value's stored ciphertext
  /// ever diverge (e.g. a key regenerated by an earlier dev session while
  /// old ciphertext was left behind), `read` throws a DOMException
  /// (`OperationError`) instead of returning null. Left unhandled, that
  /// exception breaks every API call in the app, not just authenticated
  /// ones. Treat an unreadable value the same as "not present" and wipe
  /// the broken state so the app self-heals instead of failing forever.
  Future<String?> _read(String key) async {
    try {
      return await _storage.read(key: key);
    } catch (_) {
      await clear();
      return null;
    }
  }

  /// Clears local storage unconditionally — logout must never leave a
  /// stale session behind even if the server-side revoke call fails, per
  /// MA-21 FR-5.
  Future<void> clear() async {
    await Future.wait([
      _storage.delete(key: _accessTokenKey),
      _storage.delete(key: _refreshTokenKey),
      _storage.delete(key: _accessTokenExpiresAtKey),
    ]);
  }
}
