import '../../../core/config/app_config.dart';
import '../../../core/network/api_client.dart';
import '../models/frequency.dart';

/// MA-96/MA-121 FR-2's `POST /cart/items`.
abstract class CartRepository {
  /// [idempotencyKey] is generated by the caller (ProductConfigBloc) once
  /// per confirm attempt and reused across any retry of that same attempt
  /// (MA-121 FR-2/FR-8) — this repository never generates its own, so a
  /// bloc-level retry can't accidentally mint a second key and defeat the
  /// server-side dedup this header exists for.
  Future<void> addItem({
    required String productId,
    required int quantity,
    required Frequency frequency,
    required String idempotencyKey,
    DateTime? startDate,
  });
}

class DioCartRepository implements CartRepository {
  DioCartRepository(this._client);

  final ApiClient _client;

  @override
  Future<void> addItem({
    required String productId,
    required int quantity,
    required Frequency frequency,
    required String idempotencyKey,
    DateTime? startDate,
  }) async {
    await _client.request(
      'POST',
      '${AppConfig.cartBaseUrl}/cart/items',
      headers: {'Idempotency-Key': idempotencyKey},
      body: {
        'productId': productId,
        'quantity': quantity,
        'frequency': frequency.wireValue,
        'startDate': ?startDate?.toIso8601String(),
      },
    );
  }
}
