import '../../../core/config/app_config.dart';
import '../../../core/network/api_client.dart';
import '../models/cart_line_item.dart';
import '../models/cart_view.dart';
import '../models/frequency.dart';

/// MA-96/MA-121 FR-2's `POST /cart/items`, plus MA-123's `GET`/`PUT /cart`
/// and `DELETE /cart/items/{id}` for the cart review screen.
abstract class CartRepository {
  /// [idempotencyKey] is generated by the caller (ProductConfigBloc) once
  /// per confirm attempt and reused across any retry of that same attempt
  /// (MA-121 FR-2/FR-8) — this repository never generates its own, so a
  /// bloc-level retry can't accidentally mint a second key and defeat the
  /// server-side dedup this header exists for.
  Future<void> addItem({
    required String productId,
    required int quantity,
    required Frequency frequency,
    required String idempotencyKey,
    DateTime? startDate,
  });

  /// MA-123 FR-2. Never throws for "no cart yet" — Cart Service returns
  /// `200` with an empty item list and `cartVersion: 0` in that case
  /// (`get_cart_handler.py`), not a `404`.
  Future<CartView> getCart();

  /// MA-123 FR-4. `PUT /cart` replaces the **full** item list — there is no
  /// per-item patch endpoint — so [items] must be the complete, current
  /// list with the desired change already applied. [ifVersion] is the
  /// last-known `cartVersion`; a stale value fails with a `409`
  /// (`CartRepository`'s caller is responsible for refetch-and-reapply, not
  /// this method).
  Future<CartView> updateItem({required List<CartLineItem> items, required int ifVersion});

  /// MA-123 FR-5. No response body (`204`) — Cart Service's own contract
  /// doesn't return a quote here either, matching `updateItem`'s split.
  Future<void> removeItem({required String id});
}

class DioCartRepository implements CartRepository {
  DioCartRepository(this._client);

  final ApiClient _client;

  @override
  Future<void> addItem({
    required String productId,
    required int quantity,
    required Frequency frequency,
    required String idempotencyKey,
    DateTime? startDate,
  }) async {
    await _client.request(
      'POST',
      '${AppConfig.cartBaseUrl}/cart/items',
      headers: {'Idempotency-Key': idempotencyKey},
      body: {
        'productId': productId,
        'quantity': quantity,
        'frequency': frequency.wireValue,
        'startDate': ?startDate?.toIso8601String(),
      },
    );
  }

  @override
  Future<CartView> getCart() async {
    final data = await _client.request('GET', '${AppConfig.cartBaseUrl}/cart');
    return CartView.fromJson(data);
  }

  @override
  Future<CartView> updateItem({
    required List<CartLineItem> items,
    required int ifVersion,
  }) async {
    final data = await _client.request(
      'PUT',
      '${AppConfig.cartBaseUrl}/cart',
      body: {'items': items.map((item) => item.toJson()).toList(), 'ifVersion': ifVersion},
    );
    return CartView.fromJson(data);
  }

  @override
  Future<void> removeItem({required String id}) async {
    await _client.request('DELETE', '${AppConfig.cartBaseUrl}/cart/items/$id');
  }
}
