import '../../../core/config/app_config.dart';
import '../../../core/network/api_client.dart';
import '../models/payment_method.dart';
import '../models/payment_view.dart';
import '../models/recharge_order.dart';
import '../models/wallet_view.dart';

/// MA-24's Wallet & Recharge screen data layer — talks to Wallet Service
/// (MA-127, `GET /wallet/me`, `GET /wallet/me/retry`) and Payment Service
/// (MA-126, `POST /payments`, `POST /payments/{id}/confirm`,
/// `GET /payments/{id}`).
abstract class WalletRepository {
  /// MA-127 FR-1. Never throws for "not yet provisioned" — the response
  /// carries `status: CREATING` with `balancePaise: 0` in that case, not
  /// an error (mirrors MA-1's own registration-flow convention).
  Future<WalletView> getWallet();

  /// MA-126 FR-4. Owner-scoped; used to poll a pending recharge attempt
  /// to its authoritative outcome (MA-125 FR-6 — never inferred from a
  /// wallet balance delta).
  Future<PaymentView> getPayment(String paymentId);

  /// MA-126 FR-1. [idempotencyKey] is generated by the caller (WalletBloc)
  /// once per recharge attempt and reused across any retry of that same
  /// attempt — this repository never generates its own, so a bloc-level
  /// retry can't mint a second key and defeat the server-side dedupe
  /// that header exists for.
  Future<RechargeOrder> createRecharge({
    required int amountPaise,
    required PaymentMethod method,
    required String idempotencyKey,
  });

  /// MA-126 FR-2. `razorpayOrderId` is required — the server 409s
  /// (`ORDER_MISMATCH`) if it doesn't match the order on the payment row.
  /// This call never credits the wallet; it only advances the payment to
  /// `CONFIRMING`. The credit is webhook-driven, server-side.
  Future<void> confirmRecharge({
    required String paymentId,
    required String razorpayPaymentId,
    required String razorpayOrderId,
    required String razorpaySignature,
  });

  /// MA-1 FR-3, reused as-is by the Wallet screen's "Retry setup" action
  /// (MA-125 FR-2) when `status == FAILED`.
  Future<void> retryProvision();
}

class DioWalletRepository implements WalletRepository {
  DioWalletRepository(this._client);

  final ApiClient _client;

  @override
  Future<WalletView> getWallet() async {
    final data = await _client.request('GET', '${AppConfig.walletBaseUrl}/wallet/me');
    return WalletView.fromJson(data);
  }

  @override
  Future<PaymentView> getPayment(String paymentId) async {
    final data = await _client.request(
      'GET',
      '${AppConfig.paymentBaseUrl}/payments/$paymentId',
    );
    return PaymentView.fromJson(data);
  }

  @override
  Future<RechargeOrder> createRecharge({
    required int amountPaise,
    required PaymentMethod method,
    required String idempotencyKey,
  }) async {
    final data = await _client.request(
      'POST',
      '${AppConfig.paymentBaseUrl}/payments',
      headers: {'Idempotency-Key': idempotencyKey},
      body: {
        'purpose': 'WALLET_RECHARGE',
        'amountPaise': amountPaise,
        'currency': 'INR',
        'method': method.wireValue,
      },
    );
    return RechargeOrder.fromJson(data);
  }

  @override
  Future<void> confirmRecharge({
    required String paymentId,
    required String razorpayPaymentId,
    required String razorpayOrderId,
    required String razorpaySignature,
  }) async {
    await _client.request(
      'POST',
      '${AppConfig.paymentBaseUrl}/payments/$paymentId/confirm',
      body: {
        'razorpayPaymentId': razorpayPaymentId,
        'razorpayOrderId': razorpayOrderId,
        'razorpaySignature': razorpaySignature,
      },
    );
  }

  @override
  Future<void> retryProvision() async {
    await _client.request('POST', '${AppConfig.walletBaseUrl}/wallet/me/retry');
  }
}
